name: EndOfSupport upgrade the workflow

on:
  workflow_call:
    inputs:
      # project_name is not used in the workflow, kept for backwards compatibility.
      project_name:
        type: string
        default: "sg-ci"
      excluded_jobs:
        type: string
        default: ""
      package_manager:
        type: string
        default: "npm"
      npm_token:
        type: string
        default: ""
      build_command:
        type: string
        default: "npm run build"
      docker_build_command:
        type: string
        default: ""
      docker_build_image_id:
        description: "Docker image ID as mentioned in docker_build_command"
        type: string
        default: "local:latest"
      semgrep_options:
        type: string
        default: ""
      docker_before_step_command:
        type: string
        default: ""
      docker_after_step_command:
        type: string
        default: ""
      pr_agent_before_step_command:
        type: string
        default: ""
      pr_agent_after_step_command:
        type: string
        default: ""
      security_scan_before_step_command:
        type: string
        default: ""
      security_scan_after_step_command:
        type: string
        default: ""


jobs:
  deprecated-upgrade-the-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: EndOfSupport upgrade to the new workflow
        run: |
          echo "::error::This workflow is deprecated and disabled. Upgrade to new workflow, refer to, https://studiographene.atlassian.net/wiki/spaces/SGKB/pages/2166816769/GitHub+Change+Announcements+Deprecating+CI+Workflows+In+Favour+Of+New+Central+Workflow+15+May+24"
          exit 1
