name: studiographene-ci

on:
  workflow_call:
    inputs:
      # project_name is not used in the workflow, kept for backwards compatibility.
      project_name:
        type: string
        default: "sg-ci"
      excluded_jobs:
        type: string
        default: ""
      package_manager:
        type: string
        default: "npm"
      npm_token:
        type: string
        default: ""
      build_command:
        type: string
        default: "npm run build"
      docker_build_command:
        type: string
        default: "docker build -t local:latest ."
      docker_build_image_id:
        description: "Docker image ID as mentioned in docker_build_command"
        type: string
        default: "local:latest"
      CONTAINER_SCANNERS:
        description: "comma-separated list of what security issues to detect (vuln,secret,config). Default = vuln"
        type: string
        required: false
        default: vuln
      CONTAINER_SCAN_SKIP_DIRS:
        description: "Comma separated list of directories to skip scanning"
        type: string
        required: false
      lint_command:
        type: string
        default: "npm run lint"
      allowedLicenses:
        type: string
        default: "allowed_licenses.txt"
      semgrep_options:
        type: string
        default: ""
      danger_before_step_command:
        type: string
        default: ""
      danger_after_step_command:
        type: string
        default: ""
      semgrep_before_step_command:
        type: string
        default: ""
      semgrep_after_step_command:
        type: string
        default: ""
      sbom_before_step_command:
        type: string
        default: ""
      sbom_after_step_command:
        type: string
        default: ""
      osv_before_step_command:
        type: string
        default: ""
      osv_after_step_command:
        type: string
        default: ""
      licensescan_before_step_command:
        type: string
        default: ""
      licensescan_after_step_command:
        type: string
        default: ""
      gitleaks_before_step_command:
        type: string
        default: ""
      gitleaks_after_step_command:
        type: string
        default: ""
      run_pr_agent:
        type: string
        default: "no"
      docker_before_step_command:
        type: string
        default: ""
      docker_after_step_command:
        type: string
        default: ""
      pr_agent_before_step_command:
        type: string
        default: ""
      pr_agent_after_step_command:
        type: string
        default: ""

jobs:
  sast:
    name: SAST Scan using semgrep
    if: ${{ !contains( inputs.excluded_jobs, 'sast' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: public.ecr.aws/studiographene/ci:php-8.3-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
      - name: Semgrep before step
        if: ${{ inputs.semgrep_before_step_command != '' }}
        run: |
          ${{ inputs.semgrep_before_step_command}}
      - name: SAST Scan
        id: generate_report
        run: |
          semgrep scan --config "p/default" --sarif ${{ inputs.semgrep_options }} > semgrep.sarif

          csvData=$(node - << EOF
          const fs = require('fs');
          const sarifFile = fs.readFileSync("semgrep.sarif", 'utf8');
          const sarifData = JSON.parse(sarifFile);

          const tableData = [];

          for (const run of sarifData.runs) {
            for (const result of run.results) {
              let ruleId = result.ruleId.replaceAll(',',';');
              ruleId = ruleId.replaceAll('\n','');
              let message = result.message.text.replaceAll(',', ';');
              message = message.replaceAll('\n','');
              const severity = result.level;
              const location = result.locations[0].physicalLocation;
              const lineNumber = location.region.startLine;
              const fileName = location.artifactLocation.uri;
              // Add data to the tableData array
              tableData.push(ruleId + "|" + message +"|" + lineNumber + "|" + fileName);
            }
          }                  
          // Log the CSV data as a string
          const csvData = tableData.join('\n');
          console.log(csvData);
          EOF
          )

          # Append the CSV data to the output file
          echo 'report<<EOF' >> $GITHUB_OUTPUT
          echo "$csvData" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - uses: mshick/add-pr-comment@v2
        with:
          message-id: sast-scan
          message: "### Semgrep Report \n
            Below are the issues found by semgrep: \n
            \n\nRule Id | Message | Line Number | File Name \n
            --- | --- | --- | --- \n
            ${{steps.generate_report.outputs.report}}\n\n
            "
      - name: Semgrep after step
        if: ${{ inputs.semgrep_after_step_command != '' }}
        run: |
          ${{ inputs.semgrep_after_step_command}}

  sbom:
    name: SBOM Generator using CycloneDX
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: public.ecr.aws/studiographene/ci:php-8.3-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
      - name: SBOM before step
        if: ${{ inputs.sbom_before_step_command != '' }}
        run: |
          ${{ inputs.sbom_before_step_command}}
      - name: generate sbom
        run: |
          cdxgen -r -o bom.xml -p
        env:
          FETCH_LICENSE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CDXGEN_DEBUG_MODE: debug
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: bom.xml
      - name: SBOM after step
        if: ${{ inputs.sbom_after_step_command != '' }}
        run: |
          ${{ inputs.sbom_after_step_command}}

  dependency_scan:
    name: Dependency Scan using Google OSV
    needs: sbom
    if: ${{ !contains( inputs.excluded_jobs, 'dependency_scan' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: public.ecr.aws/studiographene/ci:php-8.3-alpine
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: .
      - name: osv before step
        if: ${{ inputs.osv_before_step_command != '' }}
        run: |
          ${{ inputs.osv_before_step_command}}
      - name: OSV Scan
        run: |
          osv-scanner --format table --config=/root/configs/osv/config.toml --sbom=bom.xml
      - name: osv after step
        if: ${{ inputs.osv_after_step_command != '' }}
        run: |
          ${{ inputs.osv_after_step_command}}

  licenseScan:
    name: LicenseScan using studiographene-cli
    needs: sbom
    if: ${{ !contains( inputs.excluded_jobs, 'licenseScan' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_OWNER: ${{ github.repository_owner }}
    container:
      image: public.ecr.aws/studiographene/ci:php-8.3-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
      - name: LicenseScan before step
        if: ${{ inputs.licensescan_before_step_command != '' }}
        run: |
          ${{ inputs.licensescan_before_step_command}}
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: .
      - name: License Scan
        run: |
          /root/executables/ci-utility check --sbom bom.xml --allowedLicences ${{ inputs.allowedLicenses }}

      - name: LicenseScan after step
        if: ${{ inputs.licensescan_after_step_command != '' }}
        run: |
          ${{ inputs.licensescan_after_step_command}}

  gitleaks:
    name: Secrets scan using Gitleaks
    if: ${{ !contains( inputs.excluded_jobs, 'gitleaks' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gitleaks before step
        if: ${{ inputs.gitleaks_before_step_command != '' }}
        run: |
          ${{ inputs.gitleaks_before_step_command}}
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: gitleaks after step
        if: ${{ inputs.gitleaks_after_step_command != '' }}
        run: |
          ${{ inputs.gitleaks_after_step_command }}

  docker:
    name: Docker build check
    if: ${{ !contains( inputs.excluded_jobs, 'docker' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
      - name: before step
        if: ${{ inputs.docker_before_step_command != '' }}
        run: |
          ${{ inputs.docker_before_step_command }}
      - name: Docker Build
        run: |
          ${{ inputs.docker_build_command }}
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Creating Trivy report PR comment template file
        run: |
          cat <<EOF >> prcomment.tpl 
          | Package | Vulnerability | Severity | Status | Installed Version | Fixed Version | Title | \n
          | ------- | ------------- | -------- | ------ | ----------------- | ------------- | ----- |
          {{- range .}}
          {{- range .Vulnerabilities}}
          \n | {{ .PkgName | html }} | {{ .VulnerabilityID | html }} | {{ .Severity | html }} | {{ .Status | html }} | {{ .InstalledVersion | html }} | {{ .FixedVersion | html }} | {{ .Title | html }} |
          {{ end }}
          {{- end }}
          EOF
      - name: Trivy container vulnerability scan
        id: container_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.docker_build_image_id }}
          format: "template"
          template: "@prcomment.tpl"
          output: "trivyreport.json"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          scanners: ${{ inputs.CONTAINER_SCANNERS }}
          skip-dirs: ${{ inputs.CONTAINER_SCAN_SKIP_DIRS }}
      - name: Report vulnerabilities in PR
        if: failure() && steps.container_scan.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo -n "{\"body\":\"### Container Vulnerabilities Detected\nThe following vulnerabilities of HIGH or CRITICAL severity has been detected in the container. Please resolve these before merging the pull request.\n\n" > result.json
          cat trivyreport.json >> result.json
          echo "\"}" >> result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json

      - name: Report no vulnerabilities in PR
        if: success() && steps.container_scan.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo -n "{\"body\":\"### No vulnerabilities detected\nNo vulnerabilities of HIGH or CRITICAL severity has been detected in the code.\"}" > result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json
      - name: after step
        if: ${{ inputs.docker_after_step_command != '' }}
        run: |
          ${{ inputs.docker_after_step_command }}

  pr_agent:
    name: Run pr agent on every pull request, respond to user comments
    if: ${{ ( inputs.run_pr_agent == 'yes' ) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - name: PR agent before step
        if: ${{ inputs.pr_agent_before_step_command != '' }}
        run: |
          ${{ inputs.pr_agent_before_step_command}}
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: PR agent after step
        if: ${{ inputs.pr_agent_after_step_command != '' }}
        run: |
          ${{ inputs.pr_agent_after_step_command}}
